application: car-yu
version: 1
runtime: python27
api_version: 1
threadsafe: no
libraries:
- name: jinja2
  version: latest

handlers: 
- url: /static
  static_dir: static
- url: /.*
  script: helloworld.py
  login: required
